### ISSUE TITLE
Add vmfolder to the vSphere:VM resource.

### ISSUE THREAD

**Issue by bretthamilton** [devblackops/POSHOrigin#7]
This is exactly what I was looking for.  I was considering upgrading my build code to DSC format but you did it first.

A request. Please add vmfolder to the vSphere:VM resource.

**Comment by devblackops** [comment]
Thank you. I'm glad you like it. The vSphere:VM resource lives in the [POSHOrigin_vSphere](https://github.com/devblackops/POSHOrigin_vSphere) module so I've added the [issue](https://github.com/devblackops/POSHOrigin_vSphere/issues/11) to that repo.

**Comment by devblackops** [comment]
BTW, have you tried using the resource? I'm curious to know what others think of it. The VM folder support is almost done as well.

**Comment by bretthamilton** [comment]
I haven't started using yet.  I am building my use cases for further
support of dsc in my company.

I am still very new to the technology but from the research I've been doing
I want to start rewriting many of my processes to use this format.  When
time allows I intend on upgrading my vm build script to use your dsc
resources.

Thanks for the message.

Brett.

**Comment by devblackops** [comment]
VM folder support has been added to the latest version of POSHOrigin_vSphere (1.1.8). You can get that version [here](https://github.com/devblackops/POSHOrigin_vSphere) or from the PowerShell Gallery [here](https://www.powershellgallery.com/packages/POSHOrigin_vSphere/1.1.8). Let me know if that works for you.

**Comment by bretthamilton** [comment]
Hey Brandon.
I took a shot at this yesterday.  Frankly it didn't go well.  I took a few
steps in the right direction...  But after a few hours, I didn't get very
far.  Maybe you have seen some of things things and you can offer some
advice.

Modules.  I seem to be having a problem with the powercli modules.  (I
downloaded the latest and used the automatic onstaller).  In my ps session
I go...  "get-module -listavailable"  it will list the various vmware
modules.  How ever when I execute you code it complains they are missing.
I tried to do some debugging.  I can include the path to the references...
But then that didn't seem to fix it either.

I took a step back and tried to do these similar actions through dsc script
resources.  I quickly realized a few things about variable scopes in DSC. I
now sympathize a bit more with the challenges of doing this.

Do you have any advice?  Do I need to register the modules some how? I can
send examples if that would help.  I might be doing something obvious.

Any help would be appreciated.

Brett.

**Comment by devblackops** [comment]
I'm sorry you're having problems. Can you try running the below from a vanilla PS console (not PowerCLI)?

``` powershell
Get-Module -Name 'VMware*' -ListAvailable
```

Also make sure you are running PowerCLI 6 R3. I remember that the R1 release was adding PowerCLI to the user's PSModulePath rather than the machine. (http://www.lucd.info/2015/08/12/fixing-a-minor-powercli-6-r1-issue/). This would cause DSC (which runs under system) to not be able to find the PowerCLI modules. Internally in the POSHOrigin_vSphere DSC resource, I'm running the following to load PowerCLI within the DSC session:

``` powershell
if ($null -ne (Get-Module -Name VMware.VimAutomation* -ListAvailable -ErrorAction SilentlyContinue -Verbose:$false)) {
   Import-Module Vmware.VimAutomation.Sdk -Verbose:$false
   Import-Module VMware.VimAutomation.Core -Verbose:$false
   Import-Module VMware.VimAutomation.Vds -Verbose:$false
} else {
    Throw 'VMware PowerCLI modules do not appear to be installed on this system.'
}
```

If you're seeing the error I throw than this is probably the issue.

Hope that helps.
Brandon

**Comment by bretthamilton** [comment]
Ok.  Yes.  I read your code nd tracked the error to that spot.  I'll give
that a shot next.

Thanks.

Brett.

**Comment by devblackops** [comment]
Did that work out for you or are you still having a problem? Happy to help.
