### ISSUE TITLE
Invoke-POSHOrigin - "_CompileConfig : A parameter cannot be found that matches parameter name 'WhatIf'."

### ISSUE THREAD

**Issue by DoctorBooM** [devblackops/POSHOrigin#9]
Hello,

I have a problem when I try to execute the  "Invoke-POSHOrigin" command like in your example.

![invoke-poshorigin](https://cloud.githubusercontent.com/assets/19287725/15149013/334e3cee-16c8-11e6-97e0-a3f4b434bad8.PNG)

Thanx for help ...

**Comment by devblackops** [comment]
Well that's embarrassing :smile: 

I just put in a change that should fix this [here](https://github.com/devblackops/POSHOrigin/releases/tag/v1.5.11). Can you download version **1.5.11** and let me know if that works for you?

Thanks

**Comment by DoctorBooM** [comment]
Hello,

I am sorry but now I have an error before in the process, in the Get-POSHOriginConfig command
![get-poshoriginconfig](https://cloud.githubusercontent.com/assets/19287725/15175024/bc906ab2-1764-11e6-9b44-9304b5324f57.PNG)

**Comment by devblackops** [comment]
It looks like you're trying to pipe the object `$x` to `Get-POSHoriginConfig` instead of assigning it the value from the cmdlet.

These will work:

``` powershell
$x = Get-POSHOriginConfig -Path .\createfile.ps1 -Verbose
```

or

``` powershell
$x = '.\createfile' | Get-POSHOriginConfig -Verbose
```

or

``` powershell
$x = dir | Get-POSHOriginConfig -Verbose
```

Hope that helps.

**Comment by DoctorBooM** [comment]
Hello Brandon, 

Thanx for your help. 
I can't test that before next week but when i will come back to office i will do ! 

Thanx, 

Regards, 

François. 

----- Mail original -----

De: "Brandon Olin" notifications@github.com 
À: "devblackops/POSHOrigin" POSHOrigin@noreply.github.com 
Cc: "DoctorBooM" befra@free.fr, "Author" author@noreply.github.com 
Envoyé: Mercredi 11 Mai 2016 19:26:39 
Objet: Re: [devblackops/POSHOrigin] Invoke-POSHOrigin - "_CompileConfig : A parameter cannot be found that matches parameter name 'WhatIf'." (#9) 

It looks like you're trying to pipe the object $x to Get-POSHoriginConfig instead of assigning it the value from the cmdlet. 
These will work: 
$ x = Get-POSHOriginConfig - Path .\ createfile.ps1 - Verbose 
or 
$ x = '.\createfile' | Get-POSHOriginConfig - Verbose 
or 
$ x = dir | Get-POSHOriginConfig - Verbose 
Hope that helps.

**Comment by devblackops** [comment]
v1.5.11 has been pushed to the PowerShell Gallery. Thanks for catching that embarrassing bug!
